system_test: system_test.cpp
# gcc -o fopen_test fopen_test.cpp
# $@: 目标文件名
# $^: 依赖文件名
	-$(CC) -o $@ $^
# ./fopen_test
	-./$@
# rm ./fopen_test
	-rm $@

fork_fd_test: fork_fd_test.cpp
# gcc -o fopen_test fopen_test.cpp
# $@: 目标文件名
# $^: 依赖文件名
	-$(CC) -o $@ $^
# ./fopen_test
	-./$@
# rm ./fopen_test
	-rm $@

erlou: erlou.cpp
# gcc -o fopen_test fopen_test.cpp
# $@: 目标文件名
# $^: 依赖文件名
	-$(CC) -o $@ $^
# ./fopen_test
	-./$@
# rm ./fopen_test
	-rm $@