CC:=gcc
fclose_test: fclose_test.cpp
# gcc -o fopen_test fopen_test.cpp
# $@: 目标文件名
# $^: 依赖文件名
	-$(CC) -o $@ $^
# ./fopen_test
	-./$@
# rm ./fopen_test
	-rm $@

stdin_out_test: stdin_out_test.cpp
# gcc -o fopen_test fopen_test.cpp
# $@: 目标文件名
# $^: 依赖文件名
	-$(CC) -o $@ $^
# ./fopen_test
	-./$@
# rm ./fopen_test
	-rm $@